"""change name of genre to genres

Revision ID: de160a3d99fe
Revises: f8f60b7cf87a
Create Date: 2024-12-04 23:37:25.886972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de160a3d99fe'
down_revision = 'f8f60b7cf87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.Text(), nullable=True))
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.TEXT(), nullable=True))
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
